// Category name -> catalogue code. Hand-assigned so references like NAV-014
// never shift when categories are reordered. All 45 must be unique.
export const CATEGORY_CODES = {
  "UI Fundamentals": "UIF",
  "Semantic HTML Elements": "SEM",
  "Page & Layout": "LAY",
  "Navigation": "NAV",
  "Buttons & Actions": "BTN",
  "Forms": "FRM",
  "Selection Controls": "SEL",
  "Feedback & Status": "FBK",
  "Overlays & Temporary UI": "OVL",
  "Data Display": "DAT",
  "Advanced Data Grid": "GRD",
  "Search, Filter & Query UI": "SRC",
  "Charts & Data Visualisation": "CHT",
  "Dashboard UI": "DSH",
  "Cards": "CRD",
  "Lists": "LST",
  "Project Management & Kanban": "KAN",
  "Workflow UI": "WFL",
  "Calendar & Scheduling": "CAL",
  "People, Teams & Organisations": "PPL",
  "Enterprise Application UI": "ENT",
  "Collaboration UI": "CLB",
  "Files & Documents": "FIL",
  "Notifications": "NTF",
  "Authentication & Security UI": "AUT",
  "Responsive & Mobile UI": "RSP",
  "Interaction Patterns": "INT",
  "Loading & Asynchronous States": "LOD",
  "Accessibility": "A11",
  "Interaction States": "STA",
  "Design System Terminology": "DSY",
  "Visual Design": "VIS",
  "CSS & Layout Vocabulary": "CSS",
  "Component Architecture": "ARC",
  "Application State Terminology": "APP",
  "AI & Agent UI": "AIU",
  "Performance & Rendering Concepts": "PRF",
  "Common Application Patterns": "PAT",
  "UI Anti-Patterns": "ANT",
  "Marketing & Content Site Patterns": "MKT",
  "Media & Rich Content": "MED",
  "Content Editing & Authoring": "EDT",
  "Onboarding & Help": "HLP",
  "Motion & Animation": "MOT",
  "Internationalisation & Localisation": "I18",
};

// Hand-curated. The source has no "Name / Synonym" rows, so aliases cannot
// be derived — see spec section 3.1 rule 5.
export const ALIASES = {
  "Switch": ["Toggle", "Toggle Switch"],
  "Text Input": ["Textbox", "Text Field"],
  "Combobox": ["Autocomplete", "Typeahead"],
  "Modal": ["Modal Dialog"],
  "Drawer": ["Off-canvas Panel", "Side Sheet"],
  "Toast": ["Snackbar", "Flash Message"],
  "Spinner": ["Loader", "Loading Indicator"],
  "Skeleton": ["Skeleton Screen", "Shimmer"],
  "Tab Bar": ["Tabs", "Tab Set"],
  "Topbar": ["Navbar", "Header Bar", "App Bar"],
  "Sidebar": ["Side Navigation", "Nav Rail"],
  "Breadcrumb": ["Breadcrumbs"],
  "Dropdown Menu": ["Menu", "Popup Menu"],
  "Context Menu": ["Right-click Menu"],
  "Command Palette": ["Quick Open", "Omnibox"],
  "Data Grid": ["Datagrid", "Advanced Table"],
  "Chip": ["Pill"],
  "Badge": ["Counter Badge", "Status Badge"],
  "Avatar": ["Profile Picture", "User Image"],
  "Empty State": ["Blank Slate", "Zero State"],
  "Accordion": ["Disclosure Group"],
  "Popover": ["Flyout"],
  "Tooltip": ["Hint"],
  "Carousel": ["Slider", "Slideshow"],
  "Lightbox": ["Image Viewer"],
  "Progress Bar": ["Progress Indicator"],
  "File Upload": ["File Picker", "Dropzone"],
  "Date Picker": ["Calendar Picker"],
  "Validation Message": ["Error Message", "Field Error"],
  "Kanban Board": ["Board View"],
};

// Spec section 9's curated list, with the two names that do not exist in the
// source remapped: "Tabs" -> "Tab Bar", "Chart" -> "Bar Chart".
export const CORE_NAMES = [
  "Button", "Icon Button", "Button Group", "Text Input", "Textarea", "Select",
  "Combobox", "Checkbox", "Radio Group", "Switch", "Slider", "Date Picker",
  "File Upload", "Form Group", "Validation Message", "Card", "Badge", "Chip",
  "Tag", "Avatar", "Alert", "Banner", "Toast", "Progress Bar", "Spinner",
  "Skeleton", "Empty State", "Modal", "Dialog", "Drawer", "Popover", "Tooltip",
  "Dropdown Menu", "Context Menu", "Command Palette", "Tab Bar", "Breadcrumb",
  "Pagination", "Sidebar", "Topbar", "Table", "Data Grid", "List", "Accordion",
  "Kanban Board", "Timeline", "KPI Card", "Bar Chart", "Hero Section",
  "Pricing Table", "Testimonial", "FAQ Accordion", "Feature Grid",
  "Newsletter Signup", "Contact Section", "Cookie Consent Banner", "Carousel",
  "Image Gallery", "Lightbox", "Video Player", "Map Embed",
];
